package com.live106.mars.game.db.model;

import java.util.Date;

public class Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.name
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.accountId
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.createday
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    private Date createday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.name
     *
     * @return the value of player.name
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.name
     *
     * @param name the value for player.name
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.accountId
     *
     * @return the value of player.accountId
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.accountId
     *
     * @param accountid the value for player.accountId
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.createday
     *
     * @return the value of player.createday
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public Date getCreateday() {
        return createday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.createday
     *
     * @param createday the value for player.createday
     *
     * @mbggenerated Fri Oct 23 10:39:49 CST 2015
     */
    public void setCreateday(Date createday) {
        this.createday = createday;
    }
}