/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.live106.mars.protocol.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PeerType implements org.apache.thrift.TEnum {
  PEER_TYPE_MASTER(1),
  PEER_TYPE_ACCOUNT(5),
  PEER_TYPE_GAME(10),
  PEER_TYPE_CLIENT(15),
  PEER_TYPE_DEFAULT(20);

  private final int value;

  private PeerType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PeerType findByValue(int value) { 
    switch (value) {
      case 1:
        return PEER_TYPE_MASTER;
      case 5:
        return PEER_TYPE_ACCOUNT;
      case 10:
        return PEER_TYPE_GAME;
      case 15:
        return PEER_TYPE_CLIENT;
      case 20:
        return PEER_TYPE_DEFAULT;
      default:
        return null;
    }
  }
}
