/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.live106.mars.protocol.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-23")
public class RequestSendClientPublicKey implements org.apache.thrift.TBase<RequestSendClientPublicKey, RequestSendClientPublicKey._Fields>, java.io.Serializable, Cloneable, Comparable<RequestSendClientPublicKey> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RequestSendClientPublicKey");

  private static final org.apache.thrift.protocol.TField CLIENT_PUB_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("clientPubKey", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RequestSendClientPublicKeyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RequestSendClientPublicKeyTupleSchemeFactory());
  }

  private String clientPubKey; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CLIENT_PUB_KEY((short)1, "clientPubKey");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CLIENT_PUB_KEY
          return CLIENT_PUB_KEY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CLIENT_PUB_KEY, new org.apache.thrift.meta_data.FieldMetaData("clientPubKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RequestSendClientPublicKey.class, metaDataMap);
  }

  public RequestSendClientPublicKey() {
  }

  public RequestSendClientPublicKey(
    String clientPubKey)
  {
    this();
    this.clientPubKey = clientPubKey;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RequestSendClientPublicKey(RequestSendClientPublicKey other) {
    if (other.isSetClientPubKey()) {
      this.clientPubKey = other.clientPubKey;
    }
  }

  public RequestSendClientPublicKey deepCopy() {
    return new RequestSendClientPublicKey(this);
  }

  @Override
  public void clear() {
    this.clientPubKey = null;
  }

  public String getClientPubKey() {
    return this.clientPubKey;
  }

  public void setClientPubKey(String clientPubKey) {
    this.clientPubKey = clientPubKey;
  }

  public void unsetClientPubKey() {
    this.clientPubKey = null;
  }

  /** Returns true if field clientPubKey is set (has been assigned a value) and false otherwise */
  public boolean isSetClientPubKey() {
    return this.clientPubKey != null;
  }

  public void setClientPubKeyIsSet(boolean value) {
    if (!value) {
      this.clientPubKey = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CLIENT_PUB_KEY:
      if (value == null) {
        unsetClientPubKey();
      } else {
        setClientPubKey((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CLIENT_PUB_KEY:
      return getClientPubKey();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CLIENT_PUB_KEY:
      return isSetClientPubKey();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RequestSendClientPublicKey)
      return this.equals((RequestSendClientPublicKey)that);
    return false;
  }

  public boolean equals(RequestSendClientPublicKey that) {
    if (that == null)
      return false;

    boolean this_present_clientPubKey = true && this.isSetClientPubKey();
    boolean that_present_clientPubKey = true && that.isSetClientPubKey();
    if (this_present_clientPubKey || that_present_clientPubKey) {
      if (!(this_present_clientPubKey && that_present_clientPubKey))
        return false;
      if (!this.clientPubKey.equals(that.clientPubKey))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_clientPubKey = true && (isSetClientPubKey());
    list.add(present_clientPubKey);
    if (present_clientPubKey)
      list.add(clientPubKey);

    return list.hashCode();
  }

  @Override
  public int compareTo(RequestSendClientPublicKey other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetClientPubKey()).compareTo(other.isSetClientPubKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClientPubKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientPubKey, other.clientPubKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RequestSendClientPublicKey(");
    boolean first = true;

    sb.append("clientPubKey:");
    if (this.clientPubKey == null) {
      sb.append("null");
    } else {
      sb.append(this.clientPubKey);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RequestSendClientPublicKeyStandardSchemeFactory implements SchemeFactory {
    public RequestSendClientPublicKeyStandardScheme getScheme() {
      return new RequestSendClientPublicKeyStandardScheme();
    }
  }

  private static class RequestSendClientPublicKeyStandardScheme extends StandardScheme<RequestSendClientPublicKey> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RequestSendClientPublicKey struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CLIENT_PUB_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clientPubKey = iprot.readString();
              struct.setClientPubKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RequestSendClientPublicKey struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.clientPubKey != null) {
        oprot.writeFieldBegin(CLIENT_PUB_KEY_FIELD_DESC);
        oprot.writeString(struct.clientPubKey);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RequestSendClientPublicKeyTupleSchemeFactory implements SchemeFactory {
    public RequestSendClientPublicKeyTupleScheme getScheme() {
      return new RequestSendClientPublicKeyTupleScheme();
    }
  }

  private static class RequestSendClientPublicKeyTupleScheme extends TupleScheme<RequestSendClientPublicKey> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RequestSendClientPublicKey struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetClientPubKey()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetClientPubKey()) {
        oprot.writeString(struct.clientPubKey);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RequestSendClientPublicKey struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.clientPubKey = iprot.readString();
        struct.setClientPubKeyIsSet(true);
      }
    }
  }

}

