/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.live106.mars.protocol.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-23")
public class ResponseAuthServerPublicKey implements org.apache.thrift.TBase<ResponseAuthServerPublicKey, ResponseAuthServerPublicKey._Fields>, java.io.Serializable, Cloneable, Comparable<ResponseAuthServerPublicKey> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ResponseAuthServerPublicKey");

  private static final org.apache.thrift.protocol.TField SERVER_PUB_KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("serverPubKey", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ResponseAuthServerPublicKeyStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ResponseAuthServerPublicKeyTupleSchemeFactory());
  }

  private String serverPubKey; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SERVER_PUB_KEY((short)1, "serverPubKey");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SERVER_PUB_KEY
          return SERVER_PUB_KEY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SERVER_PUB_KEY, new org.apache.thrift.meta_data.FieldMetaData("serverPubKey", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ResponseAuthServerPublicKey.class, metaDataMap);
  }

  public ResponseAuthServerPublicKey() {
  }

  public ResponseAuthServerPublicKey(
    String serverPubKey)
  {
    this();
    this.serverPubKey = serverPubKey;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ResponseAuthServerPublicKey(ResponseAuthServerPublicKey other) {
    if (other.isSetServerPubKey()) {
      this.serverPubKey = other.serverPubKey;
    }
  }

  public ResponseAuthServerPublicKey deepCopy() {
    return new ResponseAuthServerPublicKey(this);
  }

  @Override
  public void clear() {
    this.serverPubKey = null;
  }

  public String getServerPubKey() {
    return this.serverPubKey;
  }

  public void setServerPubKey(String serverPubKey) {
    this.serverPubKey = serverPubKey;
  }

  public void unsetServerPubKey() {
    this.serverPubKey = null;
  }

  /** Returns true if field serverPubKey is set (has been assigned a value) and false otherwise */
  public boolean isSetServerPubKey() {
    return this.serverPubKey != null;
  }

  public void setServerPubKeyIsSet(boolean value) {
    if (!value) {
      this.serverPubKey = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SERVER_PUB_KEY:
      if (value == null) {
        unsetServerPubKey();
      } else {
        setServerPubKey((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SERVER_PUB_KEY:
      return getServerPubKey();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SERVER_PUB_KEY:
      return isSetServerPubKey();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ResponseAuthServerPublicKey)
      return this.equals((ResponseAuthServerPublicKey)that);
    return false;
  }

  public boolean equals(ResponseAuthServerPublicKey that) {
    if (that == null)
      return false;

    boolean this_present_serverPubKey = true && this.isSetServerPubKey();
    boolean that_present_serverPubKey = true && that.isSetServerPubKey();
    if (this_present_serverPubKey || that_present_serverPubKey) {
      if (!(this_present_serverPubKey && that_present_serverPubKey))
        return false;
      if (!this.serverPubKey.equals(that.serverPubKey))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_serverPubKey = true && (isSetServerPubKey());
    list.add(present_serverPubKey);
    if (present_serverPubKey)
      list.add(serverPubKey);

    return list.hashCode();
  }

  @Override
  public int compareTo(ResponseAuthServerPublicKey other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetServerPubKey()).compareTo(other.isSetServerPubKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServerPubKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.serverPubKey, other.serverPubKey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ResponseAuthServerPublicKey(");
    boolean first = true;

    sb.append("serverPubKey:");
    if (this.serverPubKey == null) {
      sb.append("null");
    } else {
      sb.append(this.serverPubKey);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResponseAuthServerPublicKeyStandardSchemeFactory implements SchemeFactory {
    public ResponseAuthServerPublicKeyStandardScheme getScheme() {
      return new ResponseAuthServerPublicKeyStandardScheme();
    }
  }

  private static class ResponseAuthServerPublicKeyStandardScheme extends StandardScheme<ResponseAuthServerPublicKey> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ResponseAuthServerPublicKey struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SERVER_PUB_KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.serverPubKey = iprot.readString();
              struct.setServerPubKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ResponseAuthServerPublicKey struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.serverPubKey != null) {
        oprot.writeFieldBegin(SERVER_PUB_KEY_FIELD_DESC);
        oprot.writeString(struct.serverPubKey);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResponseAuthServerPublicKeyTupleSchemeFactory implements SchemeFactory {
    public ResponseAuthServerPublicKeyTupleScheme getScheme() {
      return new ResponseAuthServerPublicKeyTupleScheme();
    }
  }

  private static class ResponseAuthServerPublicKeyTupleScheme extends TupleScheme<ResponseAuthServerPublicKey> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ResponseAuthServerPublicKey struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetServerPubKey()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetServerPubKey()) {
        oprot.writeString(struct.serverPubKey);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ResponseAuthServerPublicKey struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.serverPubKey = iprot.readString();
        struct.setServerPubKeyIsSet(true);
      }
    }
  }

}

