/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.live106.mars.protocol.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SerializeType implements org.apache.thrift.TEnum {
  SERIALIZE_TYPE_THRIFT(1),
  SERIALIZE_TYPE_PROTOBUFFER(2);

  private final int value;

  private SerializeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SerializeType findByValue(int value) { 
    switch (value) {
      case 1:
        return SERIALIZE_TYPE_THRIFT;
      case 2:
        return SERIALIZE_TYPE_PROTOBUFFER;
      default:
        return null;
    }
  }
}
